name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x
      - name: Setup base env
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i -g lerna makeshift wait-on
          makeshift -r registry.npmjs.org -t $NPM_TOKEN
      - name: Run test
        run: |
          yarn
          yarn test
