name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 16.x
      - name: Setup base env
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm i -g lerna makeshift wait-on
          makeshift -r registry.npmjs.org -t $NPM_TOKEN
      - name: Run test
        run: |
          yarn
          yarn test
